### ISSUE TITLE
Delete all things airjump related

### ISSUE THREAD

**Issue by fchb1239** [ColossusYTTV/GorillaTag-PC-Mods#4]
please make sure you know what you’re doing and check a mods license before reposting it - airjump is under no license meaning default copyright laws apply. you have one week to delete this! - https://www.copyright.gov/legislation/dmca.pdf

**Comment by ColossusYTTV** [comment]
What are you going to do?

**Comment by ColossusYTTV** [comment]
Also you have to right to be messaging a 13 year old on his person email

**Comment by fchb1239** [comment]
i’m messaging from github issues..?

**Comment by ColossusYTTV** [comment]
No your not this is ColossusYTTV's Mom you have no right to be messaging
this phone and I will take action, my sun has been stressing alot lately
because he has gotten complaints from many people telling him to take down
"gorilla tag mods" and has gotten banned from many things because of this
miss understanding. I would like to ask you to get him unbanned from the
"gorilla tag competitive scene" and he will take down these "gorilla tag
mods".

**Comment by fchb1239** [comment]
because your son has stolen my code which is illegal - i won’t do anything i just want it gone

**Comment by fchb1239** [comment]
and yes i am - i am currently writing on github issues which is linked to your sons email address - i do not have the email address myself.

**Comment by ColossusYTTV** [comment]
He has told me about these people harrassing him, and that he will not take
down these "mods" until he is unbanned from the "gorilla tag competitive
scene" I suggest you talk to your manager about this because messaging my
Suns phone will not help you. And I forbid you to talk to my sun in his
YouTube comments and his discord. I have already talked to my legel team
and we are ready to make a harrassment charges against you.

**Comment by fchb1239** [comment]
legal team against me? it’s your son who is breaking the dmca copyright act of 1998 - please take down the mod that he has stolen from me. i’m not trying to start any trouble. i just want my mod that he modified to work as a cheat taken down.

**Comment by ColossusYTTV** [comment]
Will you try and talk to your manager to get him unbanned from the "Gorilla
tag competitive scene" His "Discord" is ColossusYTTV#7436, he will take
down the "mods" only then because that was his hobby and he seemed to only
enjoy himself when he was playing your game.

**Comment by fchb1239** [comment]
well i can’t really do that - i’m just a modder. but please just take them down and i’ll go

**Comment by ColossusYTTV** [comment]
We are also not trying to start trouble but instead reason. my sun if very
smart and can probably tell lemming a way to disable these "cheats/Unlocked
mods" permanently.

**Comment by fchb1239** [comment]
cool, but i just want airjump mods gone - that’s all i need.

**Comment by ColossusYTTV** [comment]
Why not I know that you are in contact with them "A haunted army", "JJoe",
"LemmingVR".

**Comment by fchb1239** [comment]
yes i can contact them - but remove airjump first

**Comment by ColossusYTTV** [comment]
No you must first get confirmation that my sun will be unbanned. Then we
will take down the "GitHub" completely.

**Comment by BzzzThe18th** [comment]
Lmao this is hilarious, wtf is a "legel team", I've only ever heard of a legal team ༼ つ ◕_◕ ༽つ

**Comment by BzzzThe18th** [comment]
Why are you replying through eMail?

**Comment by fchb1239** [comment]
Mr. Milner. Please remove my mod.

**Comment by fchb1239** [comment]
i cannot unban your son from anywhere - just remove my mod.

**Comment by fchb1239** [comment]
and then you delete a bunch of messages from the issue... why?

**Comment by Livku** [comment]
the best part is, he misspelled half the words

**Comment by fchb1239** [comment]
My “Sun” 😂

**Comment by ColossusYTTV** [comment]
Hey! Look who won this battle LOL, now half of the Gorilla Tag community cheats

**Comment by fchb1239** [comment]
And you're too embarrased of the bullshit you spewed at me back then, so you had to delete it.
Also you aren't responisble for all of them cheating.

**Comment by fchb1239** [comment]
![image](https://user-images.githubusercontent.com/29258204/226194510-cc9d11b7-e6b5-4924-91c3-7b3e9d64312f.png)

**Comment by fchb1239** [comment]
![image](https://user-images.githubusercontent.com/29258204/226194524-f9b44269-d7bf-4671-9279-772aba67098b.png)

**Comment by ColossusYTTV** [comment]
Oh yea I know im embarrassed I was like 12 LOL, im 14 now and actually have a brain. I honestly would just like to leave this in the past and just let the gtag comm be what it is

**Comment by fchb1239** [comment]
"Hey! Look who won this battle LOL, now half of the Gorilla Tag community cheats" - The guy who wants to leave this in the past

**Comment by ColossusYTTV** [comment]
Bro I wasn't expecting you to respond 💀 I just wanted to have the last word before I let this repo die

**Comment by fchb1239** [comment]
You get a mail when people interact with your post.
Pro tip: If you want to leave something in the past, then leave it in the past.

**Comment by ColossusYTTV** [comment]
K then letting this repo die now! Love youuu have a good life ig lmaooo

**Comment by MuttBust** [comment]
hello niggers

**Comment by E4zily** [comment]
"yOu HaVe OnE wEeK tO dElEtE" shut your bitch ass up

**Comment by imAcestxs** [comment]
@fchb1239 hello lets talk about how your game was decompiled for the full source

**Comment by E4zily** [comment]
me and the boys waiting for the airjump to show legal documents

**Comment by MuttBust** [comment]
hello black

**Comment by imAcestxs** [comment]
@fchb1239 we are gonna copyright fish game 💀 💀 💀

**Comment by imAcestxs** [comment]
@fchb1239 no copyright on fish game??? 💀

**Comment by fchb1239** [comment]
As a matter of fact, yes. There is copyright on Fish Game

**Comment by imAcestxs** [comment]
@fchb1239 prove it rn

**Comment by E4zily** [comment]
show legal documents

**Comment by fchb1239** [comment]
https://www.copyright.gov/legislation/dmca.pdf

**Comment by fchb1239** [comment]
Read this, and come back to me when you better understand the fundementals of copyright.

**Comment by imAcestxs** [comment]
that isnt proof show documents

**Comment by E4zily** [comment]
Read this, and come back to me when you better understand the fundementals of copyright.

**Comment by E4zily** [comment]
show documents proving that you went there and registered a trademark

**Comment by imAcestxs** [comment]
@fchb1239 show legal documents

**Comment by imAcestxs** [comment]
also why am banned from fish game?!?!?!?

**Comment by imAcestxs** [comment]
@fchb1239 stop folding

**Comment by E4zily** [comment]
damn he folded yawn

**Comment by fchb1239** [comment]
I had to go eat with my family, sorry about that
Anyway, if you have read that - you will understand how copyright works, and thereby not asking for legal documents.

To put it into simple terms (Thanks GPT-4):
"Alright kiddo, imagine you have a special toy that you made and you don't want anyone else to take it or make copies of it without your permission. The Digital Millennium Copyright Act, or DMCA, is a law that helps protect people's special creations, like music, movies, or books, on the internet. It says that if someone copies or shares these creations without permission, they can get in trouble. It also helps protect websites, like a playground, where people can share their creations, as long as they follow the rules and take down anything that doesn't belong there."
